---

- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - openjdk-17-jdk  
    - git
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - wget
    - unzip
    - python3-psycopg2

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Add current user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Start and enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes


