plugin: amazon.aws.aws_ec2
regions:
  - us-east-1  
filters:
  instance-state-name: running  # Only include running instances
keyed_groups:
  - key: tags.Name  
    prefix: tag
compose:
  ansible_host: public_ip_address  # Use the public IP address to connect
